# Generated by Django 3.0.2 on 2020-01-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribecraft', '0002_auto_20200107_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_name',
        ),
    ]
